### ISSUE TITLE
Getting an error, as this micro service is trying to access a Bluemix application

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-cloudnative-micro-inventory#8]
com.netflix.discovery.DiscoveryClient    : Can't get a response from http://microservices-refapp-eureka-chrisking.mybluemix.net/eureka/apps/INVENTORY-MICROSERVICE
Can't contact any eureka nodes - possibly a security group issue?
2016-11-08T15:05:24.711505436Z 
java.lang.RuntimeException: Bad status: 404
at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:606)
at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1596)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
2016-11-08T15:05:24.711586039Z 
2016-11-08 15:05:24.711 ERROR 1 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_INVENTORY-MICROSERVICE/172.17.0.3 - registration failedBad status: 404
2016-11-08T15:05:24.712002642Z 
java.lang.RuntimeException: Bad status: 404
at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:606)
at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1596)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
2016-11-08T15:05:24.712143973Z

**Comment by gangchen03** [comment]
Several others reported the similar issue. Ideally, the Eureka should be deployed first so the Microservices can register with it without error. In this case, the inventory microservice got the error of can't find Eureka instance, it is a harmless noise, but should be fixed. I will update the root git repository on deployment order.
